image: ruby:2.3

variables:
  JEKYLL_ENV: production

before_script:
  - cd dev/docs
  - bundle install

test:
  stage: test
  script:
  - bundle exec jekyll build -d ./../../test
  artifacts:
    paths:
    - test
  except:
  - master

pages:
  stage: deploy
  script:
  - bundle exec jekyll build -d ./../../public
  - cd ../../
  - cp www public/ -r
  artifacts:
    paths:
    - public
  only:
  - master
