image: starefossen/ruby-node

variables:
  JEKYLL_ENV: production

before_script:
  - cd dev/docs
  - bundle install
  - cd ../../

test:
  stage: test
  script:
  - cd dev/docs
  - bundle exec jekyll build -d ./../../test
  artifacts:
    paths:
    - test
  except:
  - master

pages:
  stage: deploy
  script:
  - npm install
  - npm -g install mocha mochawesome
  - bash test.sh
  - cd dev/docs
  - bundle exec jekyll build -d ./../../public
  - cd ../../
  - cp www public/ -r


  artifacts:
    paths:
    - public
  only:
  - master
