image: starefossen/ruby-node

variables:
  JEKYLL_ENV: production

stages:
  - test
  - deploy

before_script:
  - echo "Stage executing.."
  - curl "http://status.tik.co/s/calcun.blockage.core/10?title=$CI_JOB_NAME"


test:pages:
  stage: test
  script:
  - cd dev/docs
  - bundle install
  - bundle exec jekyll build -d ./../../test
  - curl "http://status.tik.co/s/calcun.blockage.core/20"

test:node:
  stage: test
  script:
  - npm install
  - npm -g install mocha mochawesome
  - bash test.sh
  - curl "http://status.tik.co/s/calcun.blockage.core/30"

  artifacts:
    paths:
    - dev/docs/tests          # preserve dev for pages
    - dev/docs/_documentation # preserve currencies exchange rates

test:coverage:
  stage: test
  script:
    - npm install
    - npm -g install mocha istanbul
    - istanbul cover _mocha ./modules/currencies/tests/*.js --timeout=20000 || true
    - mv coverage dev/docs/coverage
    - curl "http://status.tik.co/s/calcun.blockage.core/50"

  coverage: '/^Statements\s+:\s(\d+(?:\.\d+)?%)/'
  artifacts:
    paths:
    - dev/docs/coverage          # preserve dev for pages


pages:
  stage: deploy
  script:
  - cd dev/docs
  - bundle install
  - bundle exec jekyll build -d ./../../public
  - cd ../../
  - cp www public/ -r
  - curl "http://status.tik.co/s/calcun.blockage.core/80?title=BlockCore"

  artifacts:
    paths:
    - public
  dependencies:
    - test:node
    - test:coverage

  only:
  - master
