image: starefossen/ruby-node

variables:
  JEKYLL_ENV: production

stages:
  - test
  - deploy

before_script:
  - echo "Stage executing.."
  - curl "http://status.tik.co/s/calcun.blockage.core/10?title=$CI_JOB_NAME"

after_script:
  - curl "http://status.tik.co/s/calcun.blockage.core/50"

test:pages:
  stage: test
  script:
  - cd dev/docs
  - bundle install
  - bundle exec jekyll build -d ./../../test

test:node:
  stage: test
  script:
  - npm install
  - npm -g install mocha mochawesome
  - bash test.sh

  artifacts:
    paths:
    - dev/docs/tests          # preserve dev for pages

test:coverage:
  stage: test
  script:
    - npm install
    - npm -g install mocha nyc
    - nyc mocha ./modules/currencies/tests/*.js --timeout=20000 || true
  coverage: '/^Statements\s+:\s(\d+(?:\.\d+)?%)/'



pages:
  stage: deploy
  script:
  - cd dev/docs
  - bundle install
  - bundle exec jekyll build -d ./../../public
  - cd ../../
  - cp www public/ -r
  artifacts:
    paths:
    - public
  dependencies:
    - test:node
  only:
  - master
