image: starefossen/ruby-node

variables:
  JEKYLL_ENV: production

stages:
  - test
  - deploy

before_script:
  - cd dev/docs
  - bundle install
  - cd ../../


test:pages:
  stage: test
  script:
  - cd dev/docs
  - bundle exec jekyll build -d ./../../test
  - cd ../../
  except:
  - master



test:node:
  stage: test
  script:
  - cd dev/docs
  - bundle exec jekyll build -d ./../../test
  - cd ../../
  - npm install
  - npm -g install mocha mochawesome nyc
  - bash test.sh

  artifacts:
    paths:
    - dev          # preserve dev for pages
    - node_modules # preserve node_modules for test_coverage
  except:
  - master


test:coverage:
  stage: test
  script:
    - npm install
    - npm -g install mocha mochawesome nyc
    - nyc mocha ./modules/currencies/tests/*.js --timeout=20000
  coverage: '/^Statements\s+:\s(\d+(?:\.\d+)?%)/'

pages:
  stage: deploy
  script:
  - cd dev/docs
  - bundle exec jekyll build -d ./../../public
  - cd ../../
  - cp www public/ -r


  artifacts:
    paths:
    - public
  dependencies:
    - test:node
  only:
  - master
