# ----
# Site

title: CryptoCal
description: TIKAJ's Unified  Cryptocurrency API
url: https://tikaj.com
google_analytics_key:
permalink: pretty

collections:
  documentation:
    title: Documentation
    position: 1
  httpapi:
    title: HTTP APIs
    position: 2
  wsapi:
    title: WS APIs
    position: 3

gems:
  - jekyll-sitemap
  - jekyll-seo-tag

exclude:
  - readme.md
  - LICENCE

defaults:
  -
    scope:
      path: ""
    values:
      layout: default

types:
  - get
  - put
  - delete
  - post
